export const IMG_CDN_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"

export const restaurantList = [
    {
      info: {
        id: "301603",
        name: "Deepak Sweets",
        cloudinaryImageId: "svpvvnuomkntiaz2nmnu",
        areaName: "Center Point",
        costForTwo: "₹700 for two",
        cuisines: ["Sweets", "Desserts"],
        avgRating: 4.5,
        veg: true,
        parentId: "69570",
        avgRatingString: "4.5",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 37,
          lastMileTravel: 2.3,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 23:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/deepak-sweets-center-point-aligarh-301603",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "130269",
        name: "Darjeeling snacks momos point ( Center Point)",
        cloudinaryImageId: "xoo3bue8jeiozcdqqc9h",
        locality: "Marris Road",
        areaName: "Opp. Tikaram Mandir",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese", "Snacks", "Fast Food", "Pizzas", "Beverages"],
        avgRating: 4.3,
        parentId: "15412",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 40,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹50 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/darjeeling-snacks-momos-point-center-point-marris-road-opp-tikaram-mandir-aligarh-130269",
        type: "WEBLINK",
      },
    },
    
    {
      info: {
        id: "105199",
        name: "VIP Pizza Aligarh",
        cloudinaryImageId: "ezbhtrzuf1vzjav4vgxf",
        locality: "Gulzar Nagar",
        areaName: "Center Point",
        costForTwo: "₹300 for two",
        cuisines: ["Italian", "Pizzas"],
        avgRating: 4.3,
        parentId: "15531",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 43,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 22:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/vip-pizza-aligarh-gulzar-nagar-center-point-aligarh-105199",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "467014",
        name: "Sindh Sweets",
        cloudinaryImageId: "b4pnrd64ufsp6ognqr2z",
        locality: "Samad Road",
        areaName: "Opp. Tikaram Mandir",
        costForTwo: "₹250 for two",
        cuisines: ["Snacks", "Sweets", "Bakery"],
        avgRating: 4.4,
        veg: true,
        parentId: "188274",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 47,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 21:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/sindh-sweets-samad-road-opp-tikaram-mandir-aligarh-467014",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "130269",
        name: "Darjeeling snacks momos point ( Center Point)",
        cloudinaryImageId: "xoo3bue8jeiozcdqqc9h",
        locality: "Marris Road",
        areaName: "Opp. Tikaram Mandir",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese", "Snacks", "Fast Food", "Pizzas", "Beverages"],
        avgRating: 4.3,
        parentId: "15412",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 40,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹50 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/darjeeling-snacks-momos-point-center-point-marris-road-opp-tikaram-mandir-aligarh-130269",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "467014",
        name: "Sindh Sweets",
        cloudinaryImageId: "b4pnrd64ufsp6ognqr2z",
        locality: "Samad Road",
        areaName: "Opp. Tikaram Mandir",
        costForTwo: "₹250 for two",
        cuisines: ["Snacks", "Sweets", "Bakery"],
        avgRating: 4.4,
        veg: true,
        parentId: "188274",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 47,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 21:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/sindh-sweets-samad-road-opp-tikaram-mandir-aligarh-467014",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "104169",
        name: "Jassi's Breads & Bytes",
        cloudinaryImageId: "wwu1afsnwjygv1caykjh",
        locality: "Samad Road",
        areaName: "Samad Road",
        costForTwo: "₹300 for two",
        cuisines: ["Bakery", "Fast Food", "Desserts"],
        avgRating: 4.3,
        parentId: "15548",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 42,
          lastMileTravel: 2.6,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "2.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 22:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/jassis-breads-and-bytes-samad-road-aligarh-104169",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "105377",
        name: "Hot Wok",
        cloudinaryImageId: "inuizsbibieqznsctqqz",
        locality: "Landmark Shopping Mall",
        areaName: "Center Point",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese"],
        avgRating: 4,
        parentId: "4142",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 48,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-19 02:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hot-wok-landmark-shopping-mall-center-point-aligarh-105377",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "301603",
        name: "Deepak Sweets",
        cloudinaryImageId: "svpvvnuomkntiaz2nmnu",
        areaName: "Center Point",
        costForTwo: "₹700 for two",
        cuisines: ["Sweets", "Desserts"],
        avgRating: 4.5,
        veg: true,
        parentId: "69570",
        avgRatingString: "4.5",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 37,
          lastMileTravel: 2.3,
          serviceability: "SERVICEABLE",
          slaString: "35-40 mins",
          lastMileTravelString: "2.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 23:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/deepak-sweets-center-point-aligarh-301603",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "105377",
        name: "Hot Wok",
        cloudinaryImageId: "inuizsbibieqznsctqqz",
        locality: "Landmark Shopping Mall",
        areaName: "Center Point",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese"],
        avgRating: 4,
        parentId: "4142",
        avgRatingString: "4.0",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 48,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "45-50 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-19 02:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hot-wok-landmark-shopping-mall-center-point-aligarh-105377",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "105199",
        name: "VIP Pizza Aligarh",
        cloudinaryImageId: "ezbhtrzuf1vzjav4vgxf",
        locality: "Gulzar Nagar",
        areaName: "Center Point",
        costForTwo: "₹300 for two",
        cuisines: ["Italian", "Pizzas"],
        avgRating: 4.3,
        parentId: "15531",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 43,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 22:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/vip-pizza-aligarh-gulzar-nagar-center-point-aligarh-105199",
        type: "WEBLINK",
      },
    },
    
    {
      info: {
        id: "104169",
        name: "Jassi's Breads & Bytes",
        cloudinaryImageId: "wwu1afsnwjygv1caykjh",
        locality: "Samad Road",
        areaName: "Samad Road",
        costForTwo: "₹300 for two",
        cuisines: ["Bakery", "Fast Food", "Desserts"],
        avgRating: 4.3,
        parentId: "15548",
        avgRatingString: "4.3",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 42,
          lastMileTravel: 2.6,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "2.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-02-18 22:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/jassis-breads-and-bytes-samad-road-aligarh-104169",
        type: "WEBLINK",
      },
    },
    
  ];
